language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
branches:
  only:
  - develop
before_script:
  - git config --global user.name tak-bro
  - git config --global user.email env.tak@gmail.com
  - npm install -g @angular/cli
script:
  - npm run lint
  - npm run test-headless
  - npm run predeploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  repo: env-tak/env-tak.github.io
  target-branch: master
  verbose: true
  on:
    branch: develop
