language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
branches:
  only:
  - develop
before_script:
  - git config --global user.name tak-bro
  - git config --global user.email env.tak@gmail.com
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages
script:
  - npm run lint
  - npm run test-headless
after_success:
  - npm run deploy
